# fly.toml app configuration file generated for dolar-turismo on 2023-07-01T10:44:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dolar-turismo"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "5s"
